name: Run Playwright Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-playwright-runner:
    runs-on: ubuntu-latest

    steps:
      # Checka ut koden från GitHub
      - name: Checkout code
        uses: actions/checkout@v4

      # Installera Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
          cache: 'npm'

      # Installera projektberoenden
      - name: Install dependencies
        run: npm ci

      # Run Build
      - name: Build
        run: npm run build

      # Install Artillery
      - name: Install Artillery
        run: npm install -g artillery

      # Kör backend-servern
      - name: Start backend server
        run: nohup npm run backend &

      # Vänta på att backend startar
      - name: Wait for backend to start
        run: sleep 10

      # Kör `playwright-runner.js`
      - name: Run Playwright test with Artillery
        run: artillery run load-tests/basic.yml